spring.application.name=codeaxis 

app.database.name=code_axis_db
spring.datasource.url=jdbc:mysql://localhost:3306/${app.database.name}
spring.datasource.username=root
spring.datasource.password=Rohan@1405

# Validate entity mappings against database schema
spring.jpa.hibernate.ddl-auto=validate

# Disable Spring's internal DDL generation logic (aka disableautomatic schema generation)
spring.jpa.generate-ddl=false

# Disable automatic bean validation at the JPA level
# This prevents errors if your Java fields don't perfectly match your DB constraints
spring.jpa.properties.jakarta.persistence.validation.mode=none

# MySQL dialect
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect

# Logging
spring.jpa.show-sql=true
spring.jpa.open-in-view=false

spring.web.error.include-message=always

# Enable exception throwing for missing routes
spring.web.resources.add-mappings=false

# =============================================================================
# SMTP CONFIGURATION
# =============================================================================

# app.mail.smtp-enabled=true
app.mail.smtp-enabled=false
spring.mail.host=mail.fusion5-tech.com
spring.mail.port=465
spring.mail.username=rohanpotla@fusion5-tech.com
spring.mail.password=${CODE_AXIS_MAIL_PASSWORD}

spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.ssl.enable=true

# Frontend
app.frontend.base-url=http://localhost:3000
app.frontend.verify-email-path=/verify-email

# Automatically converts Java camelCase field names
# to snake_case database column names.
#
# Example:
# isEmailVerified -> is_email_verified
# emailVerifiedAt -> email_verified_at
#
# Keeps Java naming clean while matching SQL naming standards.
spring.jpa.hibernate.naming.physical-strategy=org.hibernate.boot.model.naming.CamelCaseToUnderscoresNamingStrategy

# JWT signing secret key for token generation
app.jwt.secret-key=your-super-long-256-bit-secret-key-change-this-immediately

# Access token expiration time in milliseconds (1 hour)
app.jwt.access-token-expiration-ms=3600000

# Refresh token expiration time in milliseconds (1 day)
app.jwt.refresh-token-expiration-ms=86400000

server.port=8080

spring.security.user.name=admin
spring.security.user.password=admin
spring.jpa.properties.hibernate.format_sql=true
logging.level.org.springframework.security=DEBUG
